# Generated by Django 6.0 on 2025-12-21 11:37

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("actor_type", models.CharField(max_length=32)),
                ("actor_id", models.UUIDField(null=True)),
                ("action", models.CharField(max_length=64)),
                ("target_type", models.CharField(max_length=64)),
                ("target_id", models.UUIDField(null=True)),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["actor_type", "actor_id"], name="licenses_au_actor_t_d529a9_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"], name="licenses_au_target__600ae2_idx"
                    ),
                ],
            },
        ),
    ]
