# Generated by Django 6.0 on 2025-12-22 16:04

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0002_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseActivation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("instance_identifier", models.CharField(max_length=255)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "license",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_activations",
                        to="licenses.license",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Activation",
        ),
        migrations.AddConstraint(
            model_name="licenseactivation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deactivated_at__isnull", True)),
                fields=("license", "instance_identifier"),
                name="uq_active_activation_per_instance",
            ),
        ),
    ]
