# Generated by Django 6.0 on 2025-12-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0003_licenseactivation_delete_activation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="seat_limit",
            field=models.IntegerField(default=3),
        ),
    ]
